classdef JFXStageControllerTest < matlab.unittest.TestCase
    properties
        jfxApplication; 
    end
 
    methods(TestMethodSetup)
        function setUp(testCase)
             testCase.jfxApplication = jfx4matlab.matlab.JFXApplication();
        end
    end
 
    methods(TestMethodTeardown)
        function close(testCase)
            allStageControllers =...
                testCase.jfxApplication.getAllStageControllers();
            for i = 1 : size(allStageControllers, 1);
                sceneController = allStageControllers{i, 1}...
                    .getSceneController(); 
                if(sceneController ~= -1) 
                    sceneController.forceClose();
                end
            end
        end
    end
 
    methods(Test)
        function initTest1(testCase) 
            stageController = jfx4matlab.matlab.JFXStageController(...
                testCase.jfxApplication, 'stageController');
            
            assertEqual(testCase, ...
                stageController.getJfxApplication(), ...
                testCase.jfxApplication);
            assertEqual(testCase, ...
                stageController.getTitle(), ...
                'stageController');
            assertEqual(testCase, ...
                stageController.getSceneController(), ...
                -1); 
        end
 
% TODO: When thesse tests are executed the class
% javafx.stage.Modality.<xxx> is not available. (Even in other tests) 
%        function initTest2(testCase)
%             testCase.jfxApplication = jfx4matlab.matlab.JFXApplication();
%             stageController = jfx4matlab.matlab.JFXStageController(...
%                 testCase.jfxApplication, 'stageController', ...
%                 javafx.stage.Modality.APPLICATION_MODAL);
%             
%             assertEqual(testCase, ...
%                 stageController.getJfxApplicationAdpater(), ...
%                 testCase.jfxApplication);
%             assertEqual(testCase, ...
%                 stageController.getTitle(), ...
%                 'stageController');
%         end
%         
%         function initTest3(testCase) 
%             firstStageController = jfx4matlab.matlab.JFXStageController(...
%                 testCase.jfxApplication, 'stageController');
%             
%             secondStageController = jfx4matlab.matlab.JFXStageController(...
%                 testCase.jfxApplication, 'stageController', ...
%                 javafx.stage.Modality.WINDOW_MODAL, firstStageController);
%             
%             assertEqual(testCase, ...
%                 secondStageController.getJfxApplicationAdpater(), ...
%                 testCase.jfxApplication);
%             assertEqual(testCase, ...
%                 secondStageController.getTitle(), ...
%                 'stageController');
%         end
%         
%         function initTest4(testCase) 
%             testCase.verifyError(...
%                 @()jfx4matlab.matlab.JFXStageController(...
%                 testCase.jfxApplication, 'stageController', ...
%                 javafx.stage.Modality.WINDOW_MODAL, ...
%                 [], []),...
%                 'EXCEPTION:IllegalArgument');
%         end
%         
        function showSceneTest1(testCase)
            [fxmlFilePath, ~, ~] = fileparts(mfilename('fullpath'));
            fxmlFilePath = fullfile(fxmlFilePath, '+resources',...
                'sample.fxml');
            stageController = jfx4matlab.matlab.JFXStageController(...
                testCase.jfxApplication, 'stageController');
            sceneController = jfx4matlab.matlab.JFXSceneController(...
                fxmlFilePath);
            
            stageController.showScene(sceneController); 
            
            assertEqual(testCase, size(testCase.jfxApplication. ...
                getAllStageControllers(), 1), 1);
            assertTrue(testCase, sceneController.isInitialized());
            assertEqual(testCase, stageController.getSceneController(), ...
                sceneController); 
        end
        
        function mockStageEventTest1(testCase)
            stageController = jfx4matlab.matlab.JFXStageController(...
                testCase.jfxApplication, 'stageController');
            
            testCase.verifyError(...
                @()stageController.mockStageEvent('fxId', 'action'),...
                'EXCEPTION:NoSceneSet');
        end
        
        function mockStageEventTest2(testCase)
            [fxmlFilePath, ~, ~] = fileparts(mfilename('fullpath'));
            fxmlFilePath = fullfile(fxmlFilePath, '+resources',...
                'sample.fxml');
            stageController = jfx4matlab.matlab.JFXStageController(...
                testCase.jfxApplication, 'stageController');
            sceneController = jfx4matlab.matlab.JFXSceneController(...
                fxmlFilePath);
            stageController.showScene(sceneController); 
            
            stageController.mockStageEvent('fxId', 'action');
        end
    end
end

